{application,primes,
             [{description,"Randoms generation and primes filtering"},
              {vsn,"0.1.0"},
              {registered,[primes_filter,random_generator]},
              {mod,{primes_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[{configuration,"config/primes.config"}]},
              {modules,[primes_app,primes_filter,primes_sup,random_generator]},
              {licenses,["Free"]},
              {links,[]}]}.
